version: "3.8"

services:
  web:
    container_name: web_app
    build: ./project
    # command: flask run -h 0.0.0.0
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - ./project:/usr/src/app/
    networks:
      - my-network
    ports:
      - 5000:5000
  db:
    container_name: postgres
    image: postgres:13-alpine
    networks:
      - my-network
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=abdelali
      - POSTGRES_PASSWORD=abdelali
      - POSTGRES_DB=abdelalidb

  nginx:
    container_name: nginx_server
    build: ./nginx
    networks:
      - my-network
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
networks:
  my-network
  # default:
  #   external: true
  #   name: my-network
# create the network
# docker network create -d bridge my-network
