version: "3.8"

services:
  web:
    container_name: web_app
    build: ./project
    # command: flask run -h 0.0.0.0
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - ./project:/usr/src/app/
    ports:
      - 5000:5000
  db:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=abdelali
      - POSTGRES_PASSWORD=abdelali
      - POSTGRES_DB=abdelalidb
  nginx:
    container_name: nginx_server
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
